<div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel"><?= $this->viewData['modalTitle'] ?></h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">

<form class="<?= $this->viewData['mainClass'] ?>" >
                <div class="row">
                    <div class="col">
                        <label class="control-label">First Name</label>
                        <input type="text" required class="form-control fname" placeholder="First name">
                    </div>
                    <div class="col">
                        <label class="control-label">Last Name</label>
                        <input type="text" required class="form-control lname" placeholder="Last name">
                    </div>
                </div>
                <div class="row">
                    <div class="col">
                        <label class="control-label">Date of Birth</label>
                        <input type="date" required class="form-control dob" placeholder="Date of Birth">
                    </div>
                    <div class="col">
                        <label class="control-label">Email</label>
                        <input type="email" required class="form-control email" placeholder="Email">
                    </div>
                </div>
                <div class="row">
                    <div class="col">
                        <label class="control-label">Class</label>
                        <select  class="form-control className" required id="className">
                            
                        </select>
                    </div>
                    <div class="col">
                        <label class="control-label">Guardian Name</label>
                        <input type="text" required class="form-control guardianName" placeholder="Guardian Name">
                    </div>
                </div>
                <div class="row">
                    <div class="col">
                        <label class="control-label">Phone Number</label>
                        <input type="text" pattern=".{10,12}" required class="form-control phoneNumber" placeholder="Phone Number">
                    </div>
                    <div class="col">
                        <label class="control-label">Year Joined</label>
                        <select  class="form-control yearJoined" required id="yearJoined">
                            
                        </select>
                    </div>
                </div>
                <hr/>
                <div class="row modal-buttons">
                    <div class="col text-right">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                        <button type="submit" onclick="submitModalData(event)" class="btn btn-primary <?= $this->viewData['saveBtnClass'] ?>"><?= $this->viewData['btnTitle'] ?></button>
                    </div>
                </div>
            </form>

          </div>
          
        </div>
      </div>