    <div>&nbsp; <span class="type-hint">Type atleast 3 characters to filter</span></div>
	<table id="studentTbl" class="table table-striped table-bordered" style="width:100%">
        <thead>
            <tr>
                <th class="th_id">Id</th>
                <th class="th_fname">First Name</th>
                <th class="th_lname">Last Name</th>
                <th class="th_dob">Date of Birth</th>
                <th class="th_email">Email</th>
                <th class="th_class">Class</th>
                <th class="th_gname">Guardian Name</th>
                <th class="th_phone">Phone number</th>
                <th class="th_dt_added">Date Added</th>
                <th class="th_dt_updated">Date Updated</th>
                <th class="th_year_joined">Year joined</th>
            </tr>
        </thead>
        <tbody>
            
        </tbody>
    </table>