<html>
	<head>
	  <meta charset="utf-8">
	  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
		<title>Invalid Request</title>
		<meta name="viewport" content="width=device-width">
		<link rel="stylesheet" type="text/css" href="public/assets/css/error.css">
	</head>
	<body>
		<div class="error-page-wrap">
			<article class="error-page gradient">
				<hgroup>
					<h1>404</h1>
					<h2>Invalid Request</h2>
				</hgroup>
				<a href="/" title="Back to Application" class="error-back">back</a>
			</article>
		</div>
	</body>
</html>