<!DOCTYPE html>
<html>
<head>
	<title>AJU - JRD coding test</title>
	<link rel="stylesheet" type="text/css" href="public/assets/css/jquery.dataTables.min.css">
	<link rel="stylesheet" type="text/css" href="public/assets/css/jquer-ui.css">
	<link rel="stylesheet" type="text/css" href="public/assets/css/bootstrap.css">
	<link rel="stylesheet" type="text/css" href="public/assets/css/jrd.css">

	<script type="text/javascript" src="public/assets/js/jquery.js"></script>
	<script type="text/javascript" src="public/assets/js/jquery-ui.js"></script>
	<script type="text/javascript" src="public/assets/js/bootstrap.js"></script>

	<script type="text/javascript" src="public/assets/js/jquery.dataTables.min.js"></script>

</head>
<body>
	<section class="container-fluid">
		<?php include $this->main_contents ?>
	</section>
	<script type="text/javascript" src="public/assets/js/jrd.js"></script>
</body>
</html>